version: '3'
services:
  api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
    depends_on:
      - db
  db:
    image: "postgres:9.6.3"
  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    # depends_on:
    #   - api